//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Proteus.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlCommon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Proteus.Resources.Strings.SqlCommon", typeof(SqlCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection established successfully..
        /// </summary>
        public static string ConnSuccess {
            get {
                return ResourceManager.GetString("ConnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect.
        /// </summary>
        public static string CouldNotConnect {
            get {
                return ResourceManager.GetString("CouldNotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid connection string.
        /// </summary>
        public static string InvalidConnStr {
            get {
                return ResourceManager.GetString("InvalidConnStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply a valid SQL connection string to continue..
        /// </summary>
        public static string InvalidConnStrMsg {
            get {
                return ResourceManager.GetString("InvalidConnStrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL connection.
        /// </summary>
        public static string SQLConn {
            get {
                return ResourceManager.GetString("SQLConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing connection.
        /// </summary>
        public static string TestingConnection {
            get {
                return ResourceManager.GetString("TestingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to connect using &quot;{0}&quot;....
        /// </summary>
        public static string TryingConn {
            get {
                return ResourceManager.GetString("TryingConn", resourceCulture);
            }
        }
    }
}
