<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="TheXDS.Ganymede" Version="0.5.1-beta.2" />
		<PackageReference Include="TheXDS.MCART.Security" Version="1.0.0-alpha.3" />
		<PackageReference Include="TheXDS.MCART.Security.Argon2" Version="1.0.0-alpha.3" />
		<PackageReference Include="TheXDS.MCART.TypeFactory" Version="1.0.0-alpha.3" />
		<PackageReference Include="TheXDS.MCART.ViewModelFactory" Version="1.0.0-alpha.3" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\..\lib\Triton\src\Core\Triton\Triton.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources\Strings\Common.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Common.resx</DependentUpon>
		</Compile>
		<Compile Update="Resources\Strings\Errors.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Errors.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\Strings\Common.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Common.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Strings\Errors.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Errors.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
