<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TheXDS.ServicePool" Version="2.0.1" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\lib\Triton\src\Bundles\ServicePool.Triton\ServicePool.Triton.csproj" />
    <ProjectReference Include="..\Proteus\Proteus.csproj" />
  </ItemGroup>

</Project>
