//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheXDS.Proteus.Resources.Strings.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DialogDemoView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogDemoView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheXDS.Proteus.Resources.Strings.Views.DialogDemoView", typeof(DialogDemoView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this dialog working correctly?.
        /// </summary>
        public static string AskText {
            get {
                return ResourceManager.GetString("AskText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic prompt dialogs.
        /// </summary>
        public static string BasicPromptsGroup {
            get {
                return ResourceManager.GetString("BasicPromptsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test cancellable operation dialog.
        /// </summary>
        public static string CancellableOpTest {
            get {
                return ResourceManager.GetString("CancellableOpTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times ran.
        /// </summary>
        public static string CustomDialog1 {
            get {
                return ResourceManager.GetString("CustomDialog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data entry dialogs.
        /// </summary>
        public static string DataEntryGroup {
            get {
                return ResourceManager.GetString("DataEntryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test error message.
        /// </summary>
        public static string ErrorTest {
            get {
                return ResourceManager.GetString("ErrorTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an error message..
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello world!.
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page contains a few demos on how the dialog service works in Ganymede.
        ///
        ///Ganymede implements a dialog API that can be tailored to different platforms. For WPF apps, you have access to a custom dialog system that integrates well with the program&apos;s styling and interface. It follows a principle of keeping the number of independent windows down to one, and implements a consistent theme and style for all of them.
        ///
        ///As this dialog system is expandable, the dialog service included in Ganymede.Wpf can incorp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple message boxes.
        /// </summary>
        public static string MessagesGroup {
            get {
                return ResourceManager.GetString("MessagesGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test message.
        /// </summary>
        public static string MessageTest {
            get {
                return ResourceManager.GetString("MessageTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishing connection....
        /// </summary>
        public static string OperationDemo1 {
            get {
                return ResourceManager.GetString("OperationDemo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to object {0}....
        /// </summary>
        public static string OperationDemo2 {
            get {
                return ResourceManager.GetString("OperationDemo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up....
        /// </summary>
        public static string OperationDemo3 {
            get {
                return ResourceManager.GetString("OperationDemo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        public static string OperationDemo4 {
            get {
                return ResourceManager.GetString("OperationDemo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation dialogs.
        /// </summary>
        public static string OperationsGroup {
            get {
                return ResourceManager.GetString("OperationsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test operation dialog.
        /// </summary>
        public static string OperationTest {
            get {
                return ResourceManager.GetString("OperationTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test question.
        /// </summary>
        public static string QuestionTest {
            get {
                return ResourceManager.GetString("QuestionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option {0}.
        /// </summary>
        public static string SelectDemo1 {
            get {
                return ResourceManager.GetString("SelectDemo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select option.
        /// </summary>
        public static string SelectDemo2 {
            get {
                return ResourceManager.GetString("SelectDemo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option from the combo box below:.
        /// </summary>
        public static string SelectDemo3 {
            get {
                return ResourceManager.GetString("SelectDemo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing selected.
        /// </summary>
        public static string SelectDemo4 {
            get {
                return ResourceManager.GetString("SelectDemo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No option has been selected from the prompt..
        /// </summary>
        public static string SelectDemo5 {
            get {
                return ResourceManager.GetString("SelectDemo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user selected &quot;{0}&quot;..
        /// </summary>
        public static string SelectDemo6 {
            get {
                return ResourceManager.GetString("SelectDemo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test item selection.
        /// </summary>
        public static string SelectItemTest {
            get {
                return ResourceManager.GetString("SelectItemTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special dialogs.
        /// </summary>
        public static string SpecialGroup {
            get {
                return ResourceManager.GetString("SpecialGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential input.
        /// </summary>
        public static string TestCredentialInput {
            get {
                return ResourceManager.GetString("TestCredentialInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined dialog.
        /// </summary>
        public static string TestCustomDialog {
            get {
                return ResourceManager.GetString("TestCustomDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number input.
        /// </summary>
        public static string TestIntInput {
            get {
                return ResourceManager.GetString("TestIntInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number range input.
        /// </summary>
        public static string TestIntRangeInput {
            get {
                return ResourceManager.GetString("TestIntRangeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text input.
        /// </summary>
        public static string TestTextInput {
            get {
                return ResourceManager.GetString("TestTextInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test wizard dialog.
        /// </summary>
        public static string TestWizard {
            get {
                return ResourceManager.GetString("TestWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter some text here..
        /// </summary>
        public static string TextInputPrompt {
            get {
                return ResourceManager.GetString("TextInputPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog service demo.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test warning message.
        /// </summary>
        public static string WarningTest {
            get {
                return ResourceManager.GetString("WarningTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a warning..
        /// </summary>
        public static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
    }
}
