<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="ViewModels\**" />
	  <EmbeddedResource Remove="ViewModels\**" />
	  <None Remove="ViewModels\**" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\lib\Triton\src\Bundles\ServicePool.Triton.Ef\ServicePool.Triton.Ef.csproj" />
		<ProjectReference Include="..\..\Core\Proteus.ServicePool\Proteus.ServicePool.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.203" />
	</ItemGroup>

</Project>
