<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="ViewModels\**" />
	  <EmbeddedResource Remove="ViewModels\**" />
	  <None Remove="ViewModels\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
		<PackageReference Include="TheXDS.ServicePool.Triton.Ef" Version="2.0.0-alpha.2" />
		<PackageReference Include="TheXDS.Triton.EFCore" Version="2.0.0-alpha.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core\Proteus.ServicePool\Proteus.ServicePool.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.102" />
	</ItemGroup>

</Project>
